name: Atualizar Dados

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:      # Permite execução manual
  push:                  # Adiciona trigger para pushes
    paths:              # Apenas quando houver mudanças em arquivos na pasta data
      - 'data/**'

jobs:
  atualizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permite que o workflow faça alterações no repositório
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Atualizar dados
      run: |
        python scripts/atualizar_dados.py
      
    - name: Commit e Push de novos arquivos
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Adiciona todos os arquivos novos ou modificados na pasta data
        git add data/*.csv
        
        # Verifica se há alterações para commitar
        if git diff --staged --quiet; then
          echo "Nenhuma alteração para commitar"
        else
          git commit -m "Atualização automática de dados [skip ci]"
          git push
        fi 