name: Atualizar Dados

on:
  schedule:
    - cron: '0 0 */14 * *'  # Roda a cada 14 dias à meia-noite
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  atualizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permite que o workflow faça alterações no repositório
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verificar novos reajustes
      run: |
        python scripts/atualizar_plano_saude.py
        
    - name: Commit e Push se houver alterações
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/plano_saude.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática do reajuste ANS" && git push) 